#ifndef LGW_SEARCHENTRY_ACTION_INTERFACE_INCLUDED
#define LGW_SEARCHENTRY_ACTION_INTERFACE_INCLUDED

G_BEGIN_DECLS

void lgw_searchentry_implement_actionable_interface (LgwActionableInterface *iface);

G_END_DECLS

#endif
