#ifndef LGW_SEARCHWIDGET_ACTIONABLE_INTERFACE_INCLUDED
#define LGW_SEARCHWIDGET_ACTIONABLE_INTERFACE_INCLUDED

G_BEGIN_DECLS

void lgw_searchwidget_impliment_actionable_interface (LgwActionableInterface *iface);

G_END_DECLS

#endif
