#ifndef LGW_TEXTTAGTABLE_PRIVATE_INCLUDED
#define LGW_TEXTTAGTABLE_PRIVATE_INCLUDED

G_BEGIN_DECLS

typedef enum { 
  LGW_TEXTTAGTABLE_SIGNALID_MATCH_FG,
  LGW_TEXTTAGTABLE_SIGNALID_MATCH_BG,
  LGW_TEXTTAGTABLE_SIGNALID_HEADER_FG,
  LGW_TEXTTAGTABLE_SIGNALID_HEADER_BG,
  LGW_TEXTTAGTABLE_SIGNALID_COMMENT_FG,
  TOTAL_LGW_TEXTTAGTABLE_SIGNALIDS
} LgwTextTagTableColumn;

struct _LgwTextTagTablePrivate {
  LwPreferences *preferences;
  guint signalid[TOTAL_LGW_TEXTTAGTABLE_SIGNALIDS];
};

#define LGW_TEXTTAGTABLE_GET_PRIVATE(object)(G_TYPE_INSTANCE_GET_PRIVATE ((object), LGW_TYPE_TEXTTAGTABLE, LgwTextTagTablePrivate))

G_END_DECLS

#endif

