#ifndef LGW_VOCABULARYWIDGET_MENUABLE_INTERFACE_INCLUDED
#define LGW_VOCABULARYWIDGET_MENUABLE_INTERFACE_INCLUDED

G_BEGIN_DECLS


void lgw_vocabularywidget_implement_menuable_interface (LgwMenuableInterface *iface);


G_END_DECLS

#endif
