#ifndef LGW_VOCABULARYWORDVIEW_ACTIONABLE_INTERFACE_INCLUDED
#define LGW_VOCABULARYWORDVIEW_ACTIONABLE_INTERFACE_INCLUDED

G_BEGIN_DECLS

void lgw_vocabularywordview_impliment_actionable_interface (LgwActionableInterface *iface);

G_END_DECLS

#endif

