#ifndef LGW_VOCABULARYLISTVIEW_ACTIONABLE_INTERFACE_INCLUDED
#define LGW_VOCABULARYLISTVIEW_ACTIONABLE_INTERFACE_INCLUDED

G_BEGIN_DECLS

void lgw_vocabularylistview_implement_actionable_interface (LgwActionableInterface *iface);

G_END_DECLS

#endif

