#ifndef LGW_VOCABULARYWORDSTORE_TREESORTABLE_INTERFACE_INCLUDED
#define LGW_VOCABULARYWORDSTORE_TREESORTABLE_INTERFACE_INCLUDED

G_BEGIN_DECLS

void lgw_vocabularywordstore_implement_treesortable_interface (GtkTreeSortableIface *iface);

G_END_DECLS

#endif

