#ifndef LGW_VOCABULARYLISTSTORE_TREESORTABLE_INTERFACE_INCLUDED
#define LGW_VOCABULARYLISTSTORE_TREESORTABLE_INTERFACE_INCLUDED

G_BEGIN_DECLS

void lgw_vocabularyliststore_implement_treesortable_interface (GtkTreeSortableIface *iface);

G_END_DECLS

#endif
