
GType
lw_search_flag_get_type ()
{
    static GType type = 0;

    if (G_UNLIKELY (type == 0))
    {
      static GFlagsValue values[] = {
        { LW_SEARCH_FLAG_RAW, LW_SEARCH_FLAG_NAME_RAW, LW_SEARCH_FLAG_NICK_RAW },
        { LW_SEARCH_FLAG_FURIGANA_INSENSITIVE, LW_SEARCH_FLAG_NAME_FURIGANA_INSENSITIVE, LW_SEARCH_FLAG_NICK_FURIGANA_INSENSITIVE },
        { LW_SEARCH_FLAG_CASE_INSENSITIVE, LW_SEARCH_FLAG_NAME_CASE_INSENSITIVE, LW_SEARCH_FLAG_NICK_CASE_INSENSITIVE },
        { LW_SEARCH_FLAG_STEM_INSENSITIVE, LW_SEARCH_FLAG_NAME_STEM_INSENSITIVE, LW_SEARCH_FLAG_NICK_STEM_INSENSITIVE },
        { LW_SEARCH_FLAG_ROMAJI_TO_FURIGANA, LW_SEARCH_FLAG_NAME_ROMAJI_TO_FURIGANA, LW_SEARCH_FLAG_NICK_ROMAJI_TO_FURIGANA },
        { LW_SEARCH_FLAG_USE_INDEX, LW_SEARCH_FLAG_NAME_USE_INDEX, LW_SEARCH_FLAG_NICK_USE_INDEX },
        { LW_SEARCH_FLAG_INSENSITIVE, LW_SEARCH_FLAG_NAME_INSENSITIVE, LW_SEARCH_FLAG_NICK_INSENSITIVE },
        { 0, NULL, NULL },
      };

      type = g_flags_register_static ("LwSearchFlag", values);
    }

    return type;
}
